apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: 22127471/auth-service
        ports:
        - containerPort: 3001
        env:
        - name: HOST_URL
          value: "http://coffee-and-chill.com"
        envFrom:
        - configMapRef:
            name: auth-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"