apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: 22127471/product-service
        ports:
        - containerPort: 3002
        env:
        - name: HOST_URL
          value: "http://coffee-and-chill.com"
        envFrom:
        - configMapRef:
            name: product-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"